config/routes.rb
Rails.application.routes.draw do

  # i18n
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root "homes#index"

    get '/all-comments-for-meme/:meme_id', to: 'comments#show_all_comments_for_meme'

    resources :memes do
      resources :comments do
        resources :likes
        resources :reports
      end
      resources :likes
      resources :reports
      resources :tags
    end

    resources :moderators do
      member do
        patch 'change_user_status'
      end
    end

    resources :admins do
      member do
        patch 'role_to_user'
        patch 'role_to_moderator'
        patch 'role_to_admin'
      end
    end

    resources :reports do
      member do
        patch 'change_status'
      end
    end
    
    get '/moderators', to: 'moderators#index'

    devise_for :users, controllers: {
      sessions:      "custom_sessions",
      registrations: "custom_registrations"
    }
  end

end

app/models/meme.rb
class Meme < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes,   as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_and_belongs_to_many :tags
  has_one_attached :image

  validates :lang, presence: true, length: { minimum: 2, maximum: 2 }, format: { with: /de|en/, message: "only allows en or de"}

  def tags_attr(tags)
    tags.each do |t,n|
      tag = Tag.find_by(name: n[:name])
      if tag
        self.tags << tag unless self.tags.exists?(tag[:id])
      else
        self.tags.create({name: n[:name]})
      end 
    end  
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController

  before_action :logged_in?, :blocked?
  before_action :is_moderator?, only: [:index, :show]

  def index
    @memes = Meme.all
  end

  def show
    @meme = Meme.find(params[:id])
  end

  def create
      @meme = current_user.memes.build(meme_params)
      if @meme.save
        @meme.tags_attr(params[:tag])
        redirect_to root_path
      else
        flash[:error] = t('error')
        redirect_to root_path
      end 
  end

  def destroy
    @meme = Meme.find(params[:id])
    if current_user.moderator? || current_user.admin?
      @meme.destroy 
      redirect_back(fallback_location: root_path)
		elsif current_user.id == @meme.user_id
      @meme.destroy
			redirect_to root_path
    end
  end

  private

  def meme_params
    params.require(:meme).permit(:lang, :image)
  end
end

app/views/memes/index.html.erb
<div class="w3-container">
  <div style="text-align:center;"><pre class="tab"><%= link_to t('en'), "/en/memes" %>    <%= link_to t('de'), "/de/memes" %></pre></div>
  <h1><%= t('modmin.all_memes') %></h1>
</div>
<% @memes.each do |meme| %>
  <div class="w3-cell-row">
    <div class="w3-cell w3-container">
      <p>
      <div><%= image_tag meme.image, class: 'img' %></div>
      <div><%= link_to t('modmin.show_meme'), meme_path(meme) %>
            <%= link_to t('modmin.destroy_meme'), meme_path(id: meme.id),
              method: :delete,
              data: { confirm: t('modmin.delete_msg')} %>
      </div>
      <div><h3><%= t('modmin.all_comments') %></h3> <%= render meme.comments %></div>
      </p>
    </div>
  </div>
<% end %>

app/views/memes/show.html.erb
<div class="w3-cell-row">>
  <div class="w3-cell w3-container">
    <p>
      <div><%= image_tag @meme.image, class: 'img' %></div>
      <div><%= link_to t('modmin.destroy_meme'), meme_path(@meme), method: :delete, data: { confirm: "Are you sure?" } %></div>
      <div><%= t('modmin.language') %> <%= @meme.lang %><div>
      <div><%= t('modmin.likes') %> <%= @meme.likes.count%></div>
      <div><%= t('modmin.comments') %> <%= render @meme.comments %></div>
    </p>
  </div>
</div>
        