config/routes.rb
Rails.application.routes.draw do

  # i18n
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root "homes#index"

    get '/all-comments-for-meme/:meme_id', to: 'comments#show_all_comments_for_meme'

    resources :memes do
      resources :comments do
        resources :likes
        resources :reports
      end
      resources :likes
      resources :reports
      resources :tags
    end

    resources :moderators do
      member do
        patch 'change_user_status'
      end
    end

    resources :admins do
      member do
        patch 'role_to_user'
        patch 'role_to_moderator'
        patch 'role_to_admin'
      end
    end

    resources :reports do
      member do
        patch 'change_status'
      end
    end
    
    get '/moderators', to: 'moderators#index'

    devise_for :users, controllers: {
      sessions:      "custom_sessions",
      registrations: "custom_registrations"
    }
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    MemesCleanupJob.perform_later
    @user = User.find(current_user.id) if current_user
    @meme = Meme.new
    @tag = Tag.new
    
    if params[:filter]
      case params[:filter]
      when "best_today"
        @memes = Meme.joins(:likes).group('memes.id').order('Count(likes.id) DESC').where(lang: I18n.locale, created_at: Date.today.beginning_of_day..Date.today.end_of_day)
      when "best_week"
        @memes = Meme.joins(:likes).group('memes.id').order('Count(likes.id) DESC').where(lang: I18n.locale, created_at: Date.today - 7..Date.today.end_of_day)
      when "best_month"
        @memes = Meme.joins(:likes).group('memes.id').order('Count(likes.id) DESC').where(lang: I18n.locale, created_at: Date.today - 30..Date.today.end_of_day)
      when "best_all_time"
        @memes = Meme.joins(:likes).group('memes.id').order('Count(likes.id) DESC').where(lang: I18n.locale)
      end
    elsif params[:tag]
      @memes = Tag.find_by(name: params[:tag]).memes.where(lang: I18n.locale)
    elsif params[:user]
      user_id = User.find_by(username: params[:user]).id
      @memes = Meme.where(user_id: user_id)
    else
      @memes = Meme.all.where(lang: I18n.locale).order(created_at: :desc)
    end
    prepare_statistic
    @memes = pagination(@memes)
  end

  private

  def pagination(array)
    @page = params[:page] || 1
    @limit = params[:limit] || 6
    @page = @page.to_i
    @limit = @limit.to_f
    @max_page = (array.length.to_f / @limit).ceil
    array[(@page -1) * @limit, @limit]
  end

  def prepare_statistic
    return unless current_user
    @statistic_best_memes = Meme.joins(:likes).group('memes.id').order('Count(likes.id) DESC').where(user_id: current_user.id).limit(5)
  end

end

app/helpers/homes_helper.rb
module HomesHelper

    def get_current_url_params
        url_params = ""

        if params[:filter] != nil
            url_params = url_params + "&filter="+params[:filter].to_s
        end

        if params[:tag] != nil
            url_params = url_params + "&tag="+params[:tag].to_s
        end

        if params[:user] != nil
            url_params = url_params + "&user="+params[:user].to_s
        end

        return url_params

    end
end

app/views/homes/_add-meme-btn-mobile.haml
.position-fixed.position-x-y.add-meme-btn-mobile-div
  %button.btn.bg-blue.rounded-circle.border.border-info{"type" => "button",
                                                        "data-bs-target" => "#addMemeModal",
                                                        "data-bs-toggle" => "modal"}
    %i.bi.bi-plus-lg.fs-3.color-white

app/views/homes/_errors.haml
- flash.each do |name, msg|
  .div{"class" => "alert alert-danger"}
    = msg

app/views/homes/_footer.haml
#footer.container-fluid.mt-auto
  .row
    .col-12.d-flex.align-items-center.justify-content-center.pt-4
      %p.text-center
        %span Dominik Arnolds, Gleb Bukov
        %br/
        %span Web Engineering Project
        %br/
        %span HS-RM, WS 2021/2022

app/views/homes/_main-part-meme.haml
.col-md-4
  .row.bg-main-meme
    .col-12.d-flex.justify-content-between
      %div.d-flex.align-items-center.user-name
        %i.bi.bi-person-circle.fs-2.me-2{style: "color: #808080"}
        %a{href: "#{'?user=' + meme.user.username}"}
          %span
            = meme.user.username
      %div.d-flex.align-items-center.meme-more

        .dropdown
          %button.more-btn#dropdownMenuButton1{"aria-expanded" => "false",
                                               "data-bs-toggle" => "dropdown",
                                               :type => "button"}
            %i.bi.bi-three-dots.fs-2.ms-2
          %ul.dropdown-menu{"aria-labelledby" => "dropdownMenuButton1"}
            %li
              = link_to 'Report',
                        '#',
                        class: "dropdown-item open-report-window-meme-btn",
                        "data-bs-target" => "#reportMemeModal",
                        "data-bs-toggle" => "modal",
                        "meme_id" => meme.id
            - if user_signed_in? && @user.id == meme.user_id
              %li
                %hr.dropdown-divider
              %li
                = link_to t('pages.index.delete_meme.btn-menu'),
                          {controller: "memes", action: "destroy", id: meme.id},
                          class: "dropdown-item text-danger",
                          method: :delete

    - if meme.reports.count > 3
      .col-12.position-relative
        %div.position-absolute.top-50.start-50.translate-middle.z-inx-9.w-75.text-center.text-light
          = t('pages.index.report_for_meme.cnt_mdr')
        = image_tag meme.image, class: 'w-100 blur-filter'
    - else
      .col-12
        = image_tag meme.image, class: 'w-100'
    .col-8.d-flex.align-items-center.tags
      - meme.tags.each do |tag|
        %span.me-2
          %a{href: "#{'?tag=' + tag.name}"}
            = '#' + tag.name
    .col-4.d-flex.justify-content-end.align-items-center.mt-1
      - if user_signed_in?
        .user-signed-in
      %span.me-1
        = meme.likes.count
      - if liked?(meme)
        %i.bi.bi-heart-fill.fs-3.color-light-blue.meme-like-add-remove{:meme_id => meme.id,
                                                                       :checked => true,
                                                                       :like_id => get_like(meme).id}
      - else
        %i.bi.bi-heart.fs-3.meme-like-add-remove{:meme_id => meme.id,
                                                 :checked => false}
      %span.ms-2.me-1.comments-count{:meme_id => meme.id,}
        = meme.comments.count
      %i.bi.bi-chat-left-dots.fs-3.all-comments{:meme_id => meme.id,
                                                "data-bs-target" => "#commentsModal",
                                                "data-bs-toggle" => "modal"}

app/views/homes/_modal-add-meme.haml
#addMemeModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "addMemeModal", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered.modal-fullscreen-sm-down
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.add_meme.title')
          .col-12.px-5
            = form_with model: @meme do |f|
              .mb-3.row
                %label.col-sm-3.col-form-label{:for => "memeName"}
                  = t('pages.index.add_meme.name') + ':'
                .col-sm-9
                  = f.text_field '',
                                 disabled: true,
                                 class: 'form-control',
                                 id: 'memeName'
              .mb-3.row
                %label.col-sm-3.col-form-label{:for => "memeLang"}
                  = t('pages.index.add_meme.lang') + ':'
                .col-sm-9.d-flex.align-items-center
                  .form-check.form-check-inline#memeLang
                    = f.radio_button :lang,
                                     'en',
                                     :class => 'form-check-input',
                                     :id => 'langEn',
                                     :checked => true
                    %label.form-check-label{:for => "langEn"}
                      = t('pages.index.add_meme.lang_1')
                  .form-check.form-check-inline#memeLang
                    = f.radio_button :lang,
                                     'de',
                                     :class => 'form-check-input',
                                     :id => 'langDe'
                    %label.form-check-label{:for => "langDe"}
                      = t('pages.index.add_meme.lang_2')
              .mb-3.row
                %label.col-sm-3.col-form-label{:for => "memeTag1"} Hashtag 1:
                .col-sm-9
                  //= f.text_field '', class: 'form-control', id: 'memeTag1', name: 'tags[tag1]'
                  = fields_for :tag, @tag, index: tag.id = 1 do |tag_f|
                    = tag_f.text_field :name, disabled: false, class: 'form-control', id: 'memeTag1'
              .mb-3.row
                %label.col-sm-3.col-form-label{:for => "memeTag1"} Hashtag 2:
                .col-sm-9
                  //= f.text_field '', class: 'form-control', id: 'memeTag2', name: 'tags[tag2]'
                  = fields_for :tag, @tag, index: tag.id = 2 do |tag_f|
                    = tag_f.text_field :name, disabled: false, class: 'form-control', id: 'memeTag2'
              .mb-3.row
                %label.col-sm-3.col-form-label{:for => "memeTag1"} Hashtag 3:
                .col-sm-9
                  //= f.text_field '', class: 'form-control', id: 'memeTag3', name: 'tags[tag3]'
                  = fields_for :tag, @tag, index: tag.id = 3 do |tag_f|
                    = tag_f.text_field :name, disabled: false, class: 'form-control', id: 'memeTag3'
              .mb-3.row
                .col-12
                  .input-group.mb-3
                    = f.file_field :image, :class => 'form-control', :id => 'memeImage', required: true
                    %label.input-group-text{:for => "memeImage"} Upload
              .mb-4.row
                .col-12.mb-1
                  = f.submit t('pages.index.add_meme.add_btn'), class: 'btn btn-primary w-100 rounded-pill'

app/views/homes/_modal-comments.haml
#commentsModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "commentsModalLabel", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.comments.title')
          .col-12.write-new-comment-col
            = form_with url: '/', class: 'post-comment' do |f|
              .mb-3
                = f.text_area :body,
                              required: true,
                              placeholder: t('pages.index.comments.placeholder'),
                              class: "form-control",
                              id: "commentBody"
              = f.submit t('pages.index.comments.post_btn'), class: "btn btn-primary w-100 rounded-pill"
          .col-12.mt-3
            %hr.w-100/
          .col-12.d-flex.justify-content-center.mb-1.mt-1
            %span
              = t('pages.index.comments.all_comments') + ':'
          .col-12.d-flex.justify-content-center.mt-1.pt-3.px-3.text-center.fw-bold.d-none.no-comments
            %div
              %span
                = t('pages.index.comments.no_comments') + ' :('
          .all-comments-modal.mb-3.overflow-scroll

app/views/homes/_modal-report-meme.haml
#reportMemeModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "reportMemeModal", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered.modal-fullscreen-sm-down
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.report_for_meme.title')
          .col-12.px-5
            = form_with class: "report-for-meme-form" do |f|
              .mb-3.row
                .col-sm-7
                  = t('pages.index.report_for_meme.descr') + ':'
                .col-sm-5.d-flex.align-items-center
                  .form-check
                    = f.radio_button 'report[reason]',
                                     'racism',
                                     :class => 'form-check-input',
                                     :id => 'racism',
                                     :checked => true
                    %label.form-check-label{:for => "racism"}
                      = t('pages.index.report_for_meme.reason1')
                .col-sm-5.offset-md-7.d-flex.align-items-center
                  .form-check
                    = f.radio_button 'report[reason]',
                                     'violence',
                                     :class => 'form-check-input',
                                     :id => 'violence'
                    %label.form-check-label{:for => "violence"}
                      = t('pages.index.report_for_meme.reason2')
                .col-sm-5.offset-md-7.d-flex.align-items-center
                  .form-check
                    = f.radio_button 'report[reason]',
                                     'pornography',
                                     :class => 'form-check-input',
                                     :id => 'pornography'
                    %label.form-check-label{:for => "pornography"}
                      = t('pages.index.report_for_meme.reason3')
                .col-sm-5.offset-md-7.d-flex.align-items-center
                  .form-check
                    = f.radio_button 'report[reason]',
                                     'religion',
                                     :class => 'form-check-input',
                                     :id => 'religion'
                    %label.form-check-label{:for => "religion"}
                      = t('pages.index.report_for_meme.reason4')
                .col-sm-5.offset-md-7.d-flex.align-items-center
                  .form-check
                    = f.radio_button 'report[reason]',
                                     'discrimination',
                                     :class => 'form-check-input',
                                     :id => 'discrimination'
                    %label.form-check-label{:for => "discrimination"}
                      = t('pages.index.report_for_meme.reason5')
              .mb-4.row
                .col-12.mb-1
                  = f.button t('pages.index.report_for_meme.send_btn'),
                             class: 'btn btn-primary w-100 rounded-pill send-report-meme-btn'
              -# "data-bs-dismiss" => "modal"

app/views/homes/_modal-reset-password.haml
#resetPasswordModal.modal.fade{"aria-hidden" => "true",
                               "aria-labelledby" => "resetPasswordModalLabel",
                               :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered.modal-fullscreen-sm-down
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close",
                              "data-bs-dismiss" => "modal",
                              :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.edit_user.reset_pw')
          .col-12.px-5.mb-4
            %form
              .mb-3
                %input#resetPasswordEmail.form-control{:placeholder => "Email", :type => "email"}/
              %button.btn.btn-primary.w-100.rounded-pill{:type => "submit"}
                = t('pages.index.edit_user.reset_pw')

app/views/homes/_modal-sign-in.haml
#loginModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "loginModalLabel", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.sign_in.title')
          .col-12.px-5
            = form_with model: resource, url: user_session_path, class: "sign-in-form" do |f|
              .mb-3
                = f.email_field :email,
                                required: true,
                                placeholder: t('pages.index.sign_in.email'),
                                class: "form-control",
                                id: "signInEmail"
                %span.sign-in-error
                  = t('pages.index.sign_in.error')
              .mb-3
                = f.password_field :password,
                                   required: true,
                                   placeholder: t('pages.index.sign_in.pass'),
                                   minlength: 6,
                                   class: "form-control",
                                   id: "signInPassword"
                %span.sign-in-error
                  = t('pages.index.sign_in.error')
              = f.submit t('pages.index.sign_in.sign_btn'), class: "btn btn-primary w-100 rounded-pill"
          .col-12.mt-3
            %hr.w-100/
          .col-12.d-flex.justify-content-center.mb-1.mt-1
            %span
              = t('pages.index.sign_in.ref_signup')
              = link_to t('pages.index.sign_up.title'),
                        '#',
                        "data-bs-dismiss" => "#loginModal",
                        "data-bs-target" => "#signupModal",
                        "data-bs-toggle" => "modal"
          .col-12.d-flex.justify-content-center.mb-4.mt-1
            %span
              = link_to t('pages.index.sign_in.ref_pasres'),
                        '#',
                        "data-bs-dismiss" => "#loginModal",
                        "data-bs-target" => "#resetPasswordModal",
                        "data-bs-toggle" => "modal"

app/views/homes/_modal-sign-up.haml
#signupModal.modal.fade{"aria-hidden" => "true",
                        "aria-labelledby" => "signupModalLabel",
                        :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close",
                              "data-bs-dismiss" => "modal",
                              :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.sign_up.title')
          .col-12.px-5
            = form_with model: resource, url: registration_path(resource), class: "sign-up-form" do |f|
              .mb-3
                = f.text_field :username,
                               required: true,
                               placeholder: t('pages.index.sign_up.name'),
                               class: "form-control",
                               id: "signupName"
                %span.sign-up-error-name
                  = t('pages.index.sign_up.error-name')
              .mb-3
                = f.email_field :email,
                                required: true,
                                placeholder: t('pages.index.sign_up.email'),
                                class: "form-control",
                                id: "signupEmail"
                %span.sign-up-error-email
                  = t('pages.index.sign_up.error-email')
              .mb-3
                = f.password_field :password,
                                   required: true,
                                   placeholder: t('pages.index.sign_up.pass'),
                                   minlength: 6,
                                   class: "form-control",
                                   id: "signupPassword"
              .mb-3
                = f.password_field :password_confirmation,
                                   required: true,
                                   placeholder: t('pages.index.sign_up.pass_c'),
                                   minlength: 6,
                                   class: "form-control",
                                   id: "signupConfirmPassword"
              = f.button t('pages.index.sign_up.create_btn'), class: "btn btn-primary w-100 rounded-pill"
          .col-12.mt-3
            %hr.w-100/
          .col-12.d-flex.justify-content-center.mb-4.mt-1
            %span
              = t('pages.index.sign_up.already_r')
              = link_to t('pages.index.sign_in.title'),
                        '#',
                        "data-bs-dismiss" => "#signupModal",
                        "data-bs-target" => "#loginModal",
                        "data-bs-toggle" => "modal"

app/views/homes/_modal-statistic.haml
#statisticModal.modal.fade{"aria-hidden" => "false", "aria-labelledby" => "commentsModalLabel", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered.modal-lg
    .modal-content
      .container
        .row
          - if user_signed_in?
            .col-12.d-flex.justify-content-end.mt-3
              %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
            .col-12.d-flex.justify-content-center
              %h3.fw-light
                = t('pages.index.statistic.title') + ' ' + @user.username
            .col-12.d-flex.justify-content-center
              - unless @user.blocked
                %span.text-success
                  active
              - else
                %span.text-danger
                  blocked
            .col-12.d-flex.justify-content-center.text-center.mt-3
              %span
                = t('pages.index.statistic.total_memes') + ': '
                %b
                  = @user.memes.count.to_s
              %span.mx-5
                = t('pages.index.statistic.total_comments') + ': '
                %b
                  = @user.comments.count.to_s
              %span
                = t('pages.index.statistic.total_likes') + ': '
                %b
                  = @user.likes.count.to_s

            .col-12.mt-3
              %hr.w-100/
            .col-12.d-flex.justify-content-center.mb-1.mt-3
              .row.statistic-achievement
                .col-12.d-flex.justify-content-center.mb-3
                  %span.fs-4.statistic-sub-title
                    = t('pages.index.statistic.achievements')

                -# calculate total likes, first line of achievement
                - likes_for_memes = 0
                - @statistic_best_memes.count.each {|k, v| likes_for_memes += v}
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-trophy-fill{class: "#{'bronze' if likes_for_memes > 0}"}
                  %span.ms-2
                    - if @user.memes.count > 0
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_1_like_memes')
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-trophy-fill{class: "#{'silver' if likes_for_memes > 2}"}
                  %span.ms-2
                    - if @user.memes.count > 2
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_3_like_memes')
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-trophy-fill{class: "#{'gold'   if likes_for_memes > 9}"}
                  %span.ms-2
                    - if @user.memes.count > 9
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_10_like_memes')

                -# calculate total memes, second line of achievement
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-emoji-laughing-fill{class: "#{'bronze' if @user.memes.count > 0}"}
                  %span.ms-2
                    - if @user.memes.count > 0
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_1_post_memes')
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-emoji-laughing-fill{class: "#{'silver' if @user.memes.count > 2}"}
                  %span.ms-2
                    - if @user.memes.count > 2
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_3_post_memes')
                .col-md-4.d-flex.align-items-center
                  %i.bi.bi-emoji-laughing-fill{class: "#{'gold'   if @user.memes.count > 4}"}
                  %span.ms-2
                    - if @user.memes.count > 4
                      = t('pages.index.statistic.earn_achievment')
                    - else
                      = t('pages.index.statistic.to_unlock_achievment')
                    = t('pages.index.statistic.achievment_5_post_memes')

            .col-12.mt-3.d-flex.justify-content-center
              %hr.w-50/
            .col-12.d-flex.justify-content-center.mt-3.mb-3
              %span.fs-4.statistic-sub-title
                = t('pages.index.statistic.best_memes')
            .col-12.d-flex.justify-content-center.mb-1.mt-1
              .row.statistic-best-memes
                - @statistic_best_memes.each do |meme|
                  = render 'main-part-meme', meme: meme

            .col-12.mt-3.d-flex.justify-content-center
              %hr.w-50/
            .col-12.d-flex.justify-content-center.mt-3.mb-3
              %span.fs-4.statistic-sub-title
                = t('pages.index.statistic.best_comments')
            .col-12.d-flex.justify-content-center.mb-5
              %span
                = t('pages.index.statistic.work_in_progess')

app/views/homes/_modal-user-edit.haml
#editUserModal.modal.fade{"aria-hidden" => "true",
                        "aria-labelledby" => "editUserModalLabel",
                        :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered.modal-fullscreen-sm-down
    .modal-content
      .container
        .row
          .col-12.d-flex.justify-content-end.mt-3
            %button.btn-close{"aria-label" => "Close",
                              "data-bs-dismiss" => "modal",
                              :type => "button"}
          .col-12.d-flex.justify-content-center.mb-4
            %h3.fw-light
              = t('pages.index.edit_user.title')
          .col-12.px-5
            = form_with model: resource, url: registration_path(resource), html: { method: :put } do |f|
              .mb-3
                = f.text_field :username,
                               required: true,
                               placeholder: t('pages.index.edit_user.name'),
                               autocomplete: "username",
                               class: "form-control",
                               id: "editName"
              .mb-3
                = f.email_field :email,
                                required: true,
                                placeholder: t('pages.index.edit_user.email'),
                                autocomplete: "email",
                                class: "form-control",
                                id: "editEmail"
              .mb-3
                = f.password_field :password,
                                   required: true,
                                   placeholder: t('pages.index.edit_user.pass'),
                                   minlength: 6,
                                   autocomplete: "new-password",
                                   class: "form-control",
                                   id: "editPassword"
              .mb-3
                = f.password_field :password_confirmation,
                                   required: true,
                                   placeholder: t('pages.index.edit_user.pass_c'),
                                   minlength: 6,
                                   autocomplete: "new-password",
                                   class: "form-control",
                                   id: "editConfirmPassword"
              .mb-3
                = f.password_field :current_password,
                                   required: true,
                                   placeholder: t('pages.index.edit_user.curr_pass'),
                                   minlength: 6,
                                   autocomplete: "current-password",
                                   class: "form-control",
                                   id: "editOldPassword"
              = f.submit t('pages.index.edit_user.update_btn'), class: "btn btn-primary w-100 rounded-pill"
          .col-12.mt-3
            %hr.w-100/
          .col-12.d-flex.justify-content-center.mt-1
            %span
              = t('pages.index.edit_user.rem_acc')
          .col-12.d-flex.justify-content-center.mb-4.mt-1.px-5
            = link_to t('pages.index.edit_user.rem_acc_btn'),
                      registration_path(User.new),
                      data: { confirm: "Are you sure?" },
                      method: :delete,
                      class: "btn btn-danger w-100 rounded-pill"

app/views/homes/index.haml
= javascript_pack_tag 'index.js'

.lang{'current-lang' => I18n.locale}

-# Navbar
= render 'navbar'
-#Errors
-#= render 'errors'
-# Main part
#main-part-memes.container-md.mt-6
  -# Title and filters
  = render 'main-part-title-filters'

  -# Memes
  #row-memes-main.row.gy-4
    - @memes.each do |meme|
      = render 'main-part-meme', meme: meme

-# Pagination
= render 'pagination'

-# Footer
= render 'footer'

-# Modal windows
= render 'modal-sign-in'
= render 'modal-sign-up'
= render 'modal-reset-password'
= render 'modal-user-edit'
= render 'modal-add-meme'
= render 'modal-comments'
= render 'modal-report-meme'
= render 'modal-statistic'